In [1]:
import modulus.models.graphcast
import numpy as np
import torch

In [2]:
weights = np.load('gc_weights/graphcast_0.25_37.npz')
keys = list(weights.keys())

In [3]:
graphcast_model = modulus.models.graphcast.GraphCastNet()

In [4]:
for name in keys[:]:
    if ('task_config' in name or 'model_config' in name or 'description' in name or 'license' in name):
        keys.remove(name)
print(len(keys))

264


In [5]:
used_names = []
count = 0
for name in keys:
    if 'encoder' in name:
        count+=1
        used_names.append(name)

In [6]:
for name in keys:
    if 'grid2mesh' in name and name not in used_names:
        used_names.append(name)
        count +=1

# Feature Embedder

In [7]:
weight = weights['params:grid2mesh_gnn/~_networks_builder/encoder_nodes_mesh_nodes_mlp/~/linear_0:w']

In [8]:
weight

array([[ 2.0012627e-09, -2.0863222e-09, -6.5035763e-09, ...,
         7.7418877e-10, -4.7315099e-09,  8.9211065e-09],
       [ 1.3817069e-09, -2.6980352e-08, -2.0542792e-08, ...,
         3.7405923e-09,  2.6380393e-09,  9.4668220e-09],
       [ 2.1001592e-08,  2.3363118e-08,  9.8533137e-09, ...,
        -1.9575703e-08, -2.7108118e-09,  7.5268458e-09],
       ...,
       [-1.7353545e-07,  2.9765246e-02,  3.2025841e-06, ...,
        -1.9732227e-06,  2.9953649e-02,  2.9925045e-02],
       [-4.7486191e-07, -1.6824378e-03,  2.7031369e-05, ...,
        -1.7084689e-05, -8.5541420e-03, -6.7124753e-03],
       [-1.4517897e-06, -3.6002666e-02,  3.1610623e-05, ...,
        -1.2236010e-05, -8.7237349e-03,  8.5814046e-03]], dtype=float32)

In [9]:
weight[-3:]

array([[-1.7353545e-07,  2.9765246e-02,  3.2025841e-06, ...,
        -1.9732227e-06,  2.9953649e-02,  2.9925045e-02],
       [-4.7486191e-07, -1.6824378e-03,  2.7031369e-05, ...,
        -1.7084689e-05, -8.5541420e-03, -6.7124753e-03],
       [-1.4517897e-06, -3.6002666e-02,  3.1610623e-05, ...,
        -1.2236010e-05, -8.7237349e-03,  8.5814046e-03]], dtype=float32)

Grid Nodes

In [10]:
graphcast_model.encoder_embedder.grid_node_mlp.model[0].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_nodes_grid_nodes_mlp/~/linear_0:w']).T)
graphcast_model.encoder_embedder.grid_node_mlp.model[0].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_nodes_grid_nodes_mlp/~/linear_0:b']).T)
graphcast_model.encoder_embedder.grid_node_mlp.model[2].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_nodes_grid_nodes_mlp/~/linear_1:w']).T)
graphcast_model.encoder_embedder.grid_node_mlp.model[2].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_nodes_grid_nodes_mlp/~/linear_1:b']).T)
graphcast_model.encoder_embedder.grid_node_mlp.model[3].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_nodes_grid_nodes_layer_norm:offset']))
graphcast_model.encoder_embedder.grid_node_mlp.model[3].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_nodes_grid_nodes_layer_norm:scale']))

/tmp/ipykernel_953856/576067370.py:2: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3697.)
  graphcast_model.encoder_embedder.grid_node_mlp.model[0].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_nodes_grid_nodes_mlp/~/linear_0:b']).T)


tensor([2.1807e+00, 2.7328e-01, 6.2951e-01, 1.2879e+00, 8.2819e-01, 4.4258e-01,
        1.8097e+00, 1.8346e+00, 3.8452e-01, 9.5897e-01, 7.1827e-01, 9.7724e-01,
        1.0208e+00, 8.9647e-01, 1.0777e-04, 5.1390e-01, 1.2043e+00, 8.2332e-01,
        5.2307e-01, 1.4883e+00, 8.0576e-01, 1.3321e+00, 1.3808e+00, 4.9207e-01,
        9.1150e-01, 1.1384e+00, 8.4812e-01, 1.2986e+00, 5.4555e-01, 1.2463e+00,
        7.5028e-01, 9.8640e-01, 1.0014e+00, 9.0164e-01, 1.6126e+00, 5.5257e-01,
        1.4729e+00, 4.7470e-01, 1.2209e+00, 1.1186e+00, 8.0146e-01, 7.4668e-01,
        1.2918e+00, 1.5419e+00, 9.0891e-01, 9.4459e-01, 9.3172e-01, 6.1457e-01,
        3.3891e-01, 3.4415e-01, 1.1680e+00, 2.4892e+00, 5.5112e-01, 2.0094e+00,
        6.1621e-01, 1.2654e+00, 9.4373e-02, 6.0042e-01, 6.3248e-01, 2.5289e-01,
        7.7832e-01, 1.4236e+00, 1.3773e+00, 1.3511e+00, 1.5283e+00, 1.5451e+00,
        1.5504e+00, 5.5185e-01, 1.8375e+00, 1.0129e+00, 1.0427e+00, 1.2057e+00,
        5.9850e-01, 5.4087e-01, 9.4442e-

Mesh Nodes

In [11]:
# Mesh Nodes are padded by prepending on zero
graphcast_model.encoder_embedder.mesh_node_mlp.model[0].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_nodes_mesh_nodes_mlp/~/linear_0:w'][-3:]).T)
graphcast_model.encoder_embedder.mesh_node_mlp.model[0].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_nodes_mesh_nodes_mlp/~/linear_0:b']).T)
graphcast_model.encoder_embedder.mesh_node_mlp.model[2].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_nodes_mesh_nodes_mlp/~/linear_1:w']).T)
graphcast_model.encoder_embedder.mesh_node_mlp.model[2].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_nodes_mesh_nodes_mlp/~/linear_1:b']).T)
graphcast_model.encoder_embedder.mesh_node_mlp.model[3].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_nodes_mesh_nodes_layer_norm:offset']))
graphcast_model.encoder_embedder.mesh_node_mlp.model[3].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_nodes_mesh_nodes_layer_norm:scale']))

tensor([ 2.1012e-03, -1.1948e-03, -1.6521e-03,  1.8731e-03,  1.3295e-04,
        -6.7681e-04, -2.9256e-04,  3.2803e-03,  2.4504e-04,  2.9433e-03,
        -5.5073e-04, -1.3705e-03, -2.8004e-05, -8.8642e-04,  3.5765e-03,
        -3.6217e-03, -4.5168e-04,  4.5496e-04, -3.4583e-03, -1.5369e-03,
         5.6151e-04, -3.3439e-04, -2.2318e-03,  3.3498e-04, -2.2135e-03,
         1.8249e-03, -6.4460e-04, -5.1276e-03, -8.9534e-04,  7.9869e-04,
         4.0419e-04,  1.2815e-03,  5.8222e-04,  4.9022e-03, -1.8685e-03,
        -7.0793e-05, -6.5248e-04, -3.8860e-03,  2.0150e-03,  2.2322e-04,
        -1.2241e-03, -9.2995e-04, -2.0024e-03, -2.4267e-04,  1.7809e-03,
         3.0651e-03,  1.3765e-03,  1.3941e-03, -3.7322e-04, -4.0433e-05,
         1.1569e-03, -1.4356e-03,  1.9658e-03,  1.0061e-01,  1.0993e-04,
        -2.4523e-03, -1.9104e-03, -6.6567e-04, -1.5113e-05,  2.8721e-03,
         8.7067e-04, -2.1801e-03,  1.6302e-03,  3.0995e-04, -1.5336e-03,
         6.4926e-04,  9.9442e-04, -2.3732e-04,  2.3

Mesh Edges

In [12]:
graphcast_model.encoder_embedder.mesh_edge_mlp.model[0].weight.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/encoder_edges_mesh_mlp/~/linear_0:w']).T)
graphcast_model.encoder_embedder.mesh_edge_mlp.model[0].bias.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/encoder_edges_mesh_mlp/~/linear_0:b']).T)
graphcast_model.encoder_embedder.mesh_edge_mlp.model[2].weight.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/encoder_edges_mesh_mlp/~/linear_1:w']).T)
graphcast_model.encoder_embedder.mesh_edge_mlp.model[2].bias.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/encoder_edges_mesh_mlp/~/linear_1:b']).T)
graphcast_model.encoder_embedder.mesh_edge_mlp.model[3].bias.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/encoder_edges_mesh_layer_norm:offset']))
graphcast_model.encoder_embedder.mesh_edge_mlp.model[3].weight.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/encoder_edges_mesh_layer_norm:scale']))

tensor([ 3.4040e-04,  2.9169e-01, -3.5265e-04,  1.3213e-03, -2.7004e-04,
        -4.5163e-04, -7.0074e-05, -4.7931e-04,  2.4432e-05, -4.4070e-04,
        -7.3062e-04,  2.4059e-04, -1.0266e-03,  5.7582e-04, -4.5144e-04,
         9.8399e-04, -1.4340e-03, -3.1855e-04, -3.0982e-04, -1.2122e-03,
         7.4422e-04, -6.5042e-04, -4.7905e-04,  2.1017e-04, -3.7558e-05,
        -6.0168e-04, -1.1341e-03, -1.3809e-03,  5.1294e-04, -5.6384e-04,
         3.4551e-04, -1.1033e-03, -2.2705e-04,  1.0479e-03, -3.7589e-04,
        -5.9741e-05,  1.0764e-03, -3.3653e-04,  6.5284e-04,  1.1086e-03,
         1.9315e-03,  1.9086e+00, -4.8670e-04, -2.6694e-04,  2.3684e-04,
        -7.5082e-04,  3.9807e-04,  1.8775e-03,  1.7882e-04, -2.2112e-03,
         3.0226e-04, -1.0157e-03,  6.0128e-05, -6.6742e-04,  3.7172e-04,
        -9.5515e-04,  2.4604e-04,  1.6273e-04,  1.4257e+00,  6.7022e-04,
        -1.0912e-03, -7.2530e-04, -1.7802e-04, -3.0180e-04, -2.7273e-04,
        -8.0971e-04,  2.6768e-04, -1.9741e-06, -6.1

Grid2Mesh Edges

In [13]:
graphcast_model.encoder_embedder.grid2mesh_edge_mlp.model[0].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_edges_grid2mesh_mlp/~/linear_0:w']).T)
graphcast_model.encoder_embedder.grid2mesh_edge_mlp.model[0].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_edges_grid2mesh_mlp/~/linear_0:b']).T)
graphcast_model.encoder_embedder.grid2mesh_edge_mlp.model[2].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_edges_grid2mesh_mlp/~/linear_1:w']).T)
graphcast_model.encoder_embedder.grid2mesh_edge_mlp.model[2].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_edges_grid2mesh_mlp/~/linear_1:b']).T)
graphcast_model.encoder_embedder.grid2mesh_edge_mlp.model[3].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_edges_grid2mesh_layer_norm:offset']))
graphcast_model.encoder_embedder.grid2mesh_edge_mlp.model[3].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_edges_grid2mesh_layer_norm:scale']))

tensor([ 1.9652e-01, -2.1565e-04,  6.6497e-04,  4.2561e-01,  3.3049e-01,
         4.6384e-01,  5.5018e-04,  3.2299e-01, -3.8763e-04,  6.5728e-01,
        -7.4462e-04, -8.5981e-04, -4.3082e-04,  2.9021e-01,  3.1100e-01,
         3.9225e-01,  2.7879e-03,  3.2925e-01,  4.7885e-05,  3.1779e-01,
         2.0764e-01,  4.0423e-01,  3.0578e-01, -1.9252e-04,  3.9343e-01,
         3.7888e-01, -6.2327e-04,  3.2672e-01,  2.1977e-01,  4.0035e-01,
        -8.8402e-05,  2.7748e-01,  6.7458e-01,  3.9973e-01,  3.4975e-01,
         2.8339e-01, -2.9983e-04,  2.0252e-01,  2.5982e-01, -7.1691e-04,
         5.3984e-01,  3.4586e-01,  2.1881e-04,  2.6005e-01,  3.1862e-01,
         3.3425e-01,  3.1277e-01,  2.6829e-01,  3.0729e-04, -3.2931e-04,
         3.0069e-01, -7.4291e-05,  5.2849e-04,  8.0154e-05,  2.7860e-01,
         3.2886e-01,  3.3997e-01,  3.3242e-01,  3.3479e-01,  2.1959e-01,
         3.1762e-04,  1.3168e-06,  4.1915e-06,  3.3280e-01,  2.8369e-01,
        -1.2360e-03,  3.0089e-01,  2.4510e-01,  2.8

Mesh2Grid Edges

In [14]:
graphcast_model.decoder_embedder.mesh2grid_edge_mlp.model[0].weight.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/encoder_edges_mesh2grid_mlp/~/linear_0:w']).T)
graphcast_model.decoder_embedder.mesh2grid_edge_mlp.model[0].bias.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/encoder_edges_mesh2grid_mlp/~/linear_0:b']).T)
graphcast_model.decoder_embedder.mesh2grid_edge_mlp.model[2].weight.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/encoder_edges_mesh2grid_mlp/~/linear_1:w']).T)
graphcast_model.decoder_embedder.mesh2grid_edge_mlp.model[2].bias.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/encoder_edges_mesh2grid_mlp/~/linear_1:b']).T)
graphcast_model.decoder_embedder.mesh2grid_edge_mlp.model[3].bias.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/encoder_edges_mesh2grid_layer_norm:offset']))
graphcast_model.decoder_embedder.mesh2grid_edge_mlp.model[3].weight.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/encoder_edges_mesh2grid_layer_norm:scale']))

tensor([0.4534, 0.5940, 0.2480, 0.5101, 0.1858, 0.4933, 0.2966, 1.5319, 0.4610,
        2.1668, 0.4873, 0.3529, 3.2145, 0.1775, 0.6013, 0.2379, 0.2061, 0.4907,
        0.3004, 0.2801, 0.5467, 0.4597, 0.2209, 0.6060, 0.5599, 0.5877, 0.1981,
        0.5265, 0.3235, 0.1880, 0.4346, 0.5543, 0.2387, 1.2158, 0.5386, 0.4598,
        0.5360, 0.5643, 0.1793, 0.4658, 0.3589, 0.5169, 0.3174, 0.6149, 0.2818,
        0.3677, 0.4746, 0.6177, 0.1802, 0.5489, 0.4239, 0.5024, 0.2191, 0.5575,
        0.2442, 0.5004, 0.5639, 0.2280, 0.5384, 0.5892, 0.3987, 0.3101, 0.1988,
        1.5988, 0.4015, 0.4614, 1.3550, 0.1869, 1.7088, 0.1945, 0.5035, 0.3584,
        0.5486, 0.3803, 0.4397, 0.6021, 0.2587, 0.5155, 0.3007, 0.2467, 0.3902,
        0.4141, 0.5268, 0.3712, 0.2666, 1.8020, 0.5639, 0.2954, 2.1517, 0.6198,
        0.1745, 0.6366, 0.1845, 0.4863, 0.5034, 0.3847, 0.2435, 0.1934, 0.3432,
        0.1895, 0.5333, 0.5691, 1.5309, 0.5586, 0.3241, 0.6638, 0.5386, 0.4676,
        0.3752, 0.5203, 0.7052, 0.4864, 

# Mesh Graph Encoder

Processor Edge MLP

In [15]:
graphcast_model.encoder.edge_mlp.model[0].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_edges_0_grid2mesh_mlp/~/linear_0:w']).T)
graphcast_model.encoder.edge_mlp.model[0].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_edges_0_grid2mesh_mlp/~/linear_0:b']).T)
graphcast_model.encoder.edge_mlp.model[2].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_edges_0_grid2mesh_mlp/~/linear_1:w']).T)
graphcast_model.encoder.edge_mlp.model[2].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_edges_0_grid2mesh_mlp/~/linear_1:b']).T)
graphcast_model.encoder.edge_mlp.model[3].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_edges_0_grid2mesh_layer_norm:offset']))
graphcast_model.encoder.edge_mlp.model[3].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_edges_0_grid2mesh_layer_norm:scale']))

tensor([ 9.7004e-01,  1.6895e-01,  2.9911e-01,  9.8095e-05, -1.1720e-04,
         2.7684e-01,  3.1998e-01,  1.7985e-01,  1.3636e-01,  3.7938e-02,
         1.0117e+00,  1.8177e-04,  2.4389e-01,  4.1599e-01,  3.5279e-01,
         1.7711e-05,  3.9010e-02,  5.3796e-01,  2.3981e-01, -2.0607e-05,
         5.0011e-01,  2.4054e-01,  3.5950e-01,  2.5340e-04,  4.0417e-01,
         1.1482e+00,  9.5340e-05, -6.5135e-05,  2.7896e-01,  2.3099e-01,
         4.5072e-01,  5.1398e-02,  8.4856e-01,  6.7653e-01,  2.5047e-01,
        -1.6463e-04,  1.9918e-05,  4.8536e-01,  2.9622e-01,  4.2812e-01,
         1.8642e-01, -1.0244e-04,  3.4137e-01,  1.6370e-04,  2.0177e-01,
         7.9960e-01,  3.6864e-01,  4.6687e-01, -1.2475e-04,  3.8694e-01,
         5.4063e-01,  1.0338e+00, -1.2798e-04,  2.6930e-01,  1.7790e-04,
         3.2408e-01,  4.4981e-01,  3.0625e-01,  1.4583e-01,  6.1279e-02,
        -6.1859e-05,  2.5180e-01,  2.3249e-01,  2.2609e-01,  3.2175e-01,
         4.2445e-01,  1.2912e+00,  2.8864e-01, -3.1

Processor Grid Node MLP

In [16]:
graphcast_model.encoder.src_node_mlp.model[0].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_nodes_0_grid_nodes_mlp/~/linear_0:w']).T)
graphcast_model.encoder.src_node_mlp.model[0].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_nodes_0_grid_nodes_mlp/~/linear_0:b']).T)
graphcast_model.encoder.src_node_mlp.model[2].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_nodes_0_grid_nodes_mlp/~/linear_1:w']).T)
graphcast_model.encoder.src_node_mlp.model[2].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_nodes_0_grid_nodes_mlp/~/linear_1:b']).T)
graphcast_model.encoder.src_node_mlp.model[3].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_nodes_0_grid_nodes_layer_norm:offset']))
graphcast_model.encoder.src_node_mlp.model[3].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_nodes_0_grid_nodes_layer_norm:scale']))

tensor([8.7194e-02, 1.0737e+00, 9.6040e-01, 1.1084e+00, 1.2665e+00, 1.0824e+00,
        1.8298e-01, 2.4171e-01, 1.0335e+00, 1.2663e-01, 1.0823e-01, 7.7383e-01,
        1.4245e+00, 1.0191e+00, 6.3216e-01, 8.5658e-01, 8.7381e-02, 9.0220e-01,
        1.2118e+00, 1.4432e-01, 7.5854e-01, 2.4607e+00, 2.9782e-02, 9.7533e-01,
        7.2311e-01, 1.1945e+00, 1.6454e-01, 5.8982e-02, 6.8773e-01, 8.2401e-02,
        1.0969e+00, 9.7224e-02, 2.2535e-02, 8.5638e-02, 5.2870e-01, 9.2081e-01,
        1.1979e-01, 8.7731e-01, 1.2422e+00, 5.5668e-02, 8.2354e-01, 8.9118e-01,
        1.2418e+00, 2.2350e-01, 5.6633e-01, 1.1828e-01, 3.9894e-01, 8.5580e-01,
        9.6052e-01, 1.0400e+00, 1.1599e-01, 2.0104e-01, 1.2064e+00, 1.0909e+00,
        8.6228e-01, 7.9903e-01, 8.6498e-01, 9.5098e-01, 6.2307e-01, 2.6627e-02,
        2.5661e-01, 4.4814e-01, 7.1578e-02, 9.9840e-01, 1.5066e-01, 1.1491e+00,
        1.0111e-01, 9.3657e-01, 1.1458e-02, 8.8588e-02, 1.7554e+00, 1.5754e+00,
        9.9566e-01, 8.3397e-01, 5.5454e-

Processor Mesh Node MLP

In [17]:
graphcast_model.encoder.dst_node_mlp.model[0].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_mlp/~/linear_0:w']).T)
graphcast_model.encoder.dst_node_mlp.model[0].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_mlp/~/linear_0:b']).T)
graphcast_model.encoder.dst_node_mlp.model[2].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_mlp/~/linear_1:w']).T)
graphcast_model.encoder.dst_node_mlp.model[2].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_mlp/~/linear_1:b']).T)
graphcast_model.encoder.dst_node_mlp.model[3].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_layer_norm:offset']))
graphcast_model.encoder.dst_node_mlp.model[3].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_layer_norm:scale']))

tensor([0.5466, 0.7106, 0.6939, 0.5887, 1.2617, 1.7295, 0.7706, 0.4842, 0.8169,
        0.5901, 0.6686, 0.7921, 0.7750, 1.0359, 0.6344, 1.4084, 1.1623, 0.7176,
        0.7223, 2.0005, 0.9986, 0.9289, 0.8989, 1.0801, 0.7127, 0.6101, 2.2829,
        0.6349, 0.7166, 1.7636, 0.6508, 0.6599, 0.9186, 0.3585, 1.4912, 0.7598,
        1.3560, 0.2381, 0.6810, 0.9073, 0.7710, 0.7363, 0.5700, 1.3021, 1.0312,
        0.5954, 0.7331, 1.3398, 0.7100, 0.7473, 0.7655, 0.3983, 0.7586, 1.9258,
        1.0009, 0.6129, 0.8982, 0.9364, 1.0850, 0.8387, 1.5388, 0.5398, 1.2025,
        0.4449, 1.6424, 1.2304, 0.3395, 0.6603, 0.5879, 1.2199, 0.6415, 0.2227,
        0.5613, 0.4949, 0.5791, 0.7078, 0.6727, 0.7578, 0.8817, 0.8056, 0.6660,
        0.4722, 2.1023, 0.7014, 0.9084, 0.0876, 0.3254, 0.2684, 0.8378, 0.7178,
        1.0767, 1.1151, 0.9103, 1.0636, 0.6665, 0.5018, 1.7798, 1.0291, 0.6959,
        1.5825, 1.7227, 0.9412, 1.0199, 0.3082, 0.7467, 0.7925, 0.6806, 0.8400,
        0.7000, 0.6883, 0.9985, 1.2461, 

# Processor Encoder

Mesh Edge

In [18]:
graphcast_model.processor_encoder.processor_layers[0].edge_mlp.model[0].weight.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_edges_0_mesh_mlp/~/linear_0:w'].T))
graphcast_model.processor_encoder.processor_layers[0].edge_mlp.model[0].bias.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_edges_0_mesh_mlp/~/linear_0:b'].T))
graphcast_model.processor_encoder.processor_layers[0].edge_mlp.model[2].weight.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_edges_0_mesh_mlp/~/linear_1:w'].T))
graphcast_model.processor_encoder.processor_layers[0].edge_mlp.model[2].bias.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_edges_0_mesh_mlp/~/linear_1:b'].T))
graphcast_model.processor_encoder.processor_layers[0].edge_mlp.model[3].weight.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_edges_0_mesh_layer_norm:scale']))
graphcast_model.processor_encoder.processor_layers[0].edge_mlp.model[3].bias.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_edges_0_mesh_layer_norm:offset']))

tensor([ 0.0593,  0.2842,  0.1515, -0.1151, -0.1842, -0.1257, -0.0469, -0.1350,
         0.1429,  0.0226, -0.1565, -0.1521,  0.0248, -0.1171,  0.0955,  0.0817,
         0.0254,  0.1916, -0.1132, -0.2592, -0.0448, -0.0757,  0.1624, -0.0743,
        -0.0150, -0.0530,  0.2270, -0.0797, -0.0940, -0.1701,  0.0191, -0.0392,
        -0.1035,  0.0599, -0.0018,  0.1866,  0.2202,  0.1764, -0.0008, -0.0423,
        -0.0392, -0.1738, -0.0472,  0.2162,  0.1999,  0.0882,  0.0321,  0.0706,
        -0.0971, -0.1751, -0.1090, -0.1257, -0.0789,  0.0843,  0.0673, -0.1306,
        -0.0527, -0.1250,  0.1431, -0.0981, -0.2002, -0.1664,  0.0408, -0.0734,
         0.2114, -0.0853, -0.0541, -0.0050,  0.1636,  0.0667, -0.0517, -0.0407,
        -0.0147,  0.0562, -0.0058,  0.0273,  0.0337,  0.1062,  0.1535, -0.0606,
         0.0010,  0.2085, -0.0773,  0.1103, -0.3452, -0.0034,  0.1386, -0.0084,
        -0.0675, -0.1212,  0.0278, -0.0787,  0.0513,  0.5519, -0.0359, -0.2050,
        -0.2304,  0.0848, -0.0677,  0.33

Mesh Node

In [19]:
graphcast_model.processor_encoder.processor_layers[1].node_mlp.model[0].weight.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_mlp/~/linear_0:w'].T))
graphcast_model.processor_encoder.processor_layers[1].node_mlp.model[0].bias.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_mlp/~/linear_0:b'].T))
graphcast_model.processor_encoder.processor_layers[1].node_mlp.model[2].weight.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_mlp/~/linear_1:w'].T))
graphcast_model.processor_encoder.processor_layers[1].node_mlp.model[2].bias.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_mlp/~/linear_1:b'].T))
graphcast_model.processor_encoder.processor_layers[1].node_mlp.model[3].weight.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_layer_norm:scale']))
graphcast_model.processor_encoder.processor_layers[1].node_mlp.model[3].bias.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_layer_norm:offset']))

tensor([ 2.7687e-03, -6.0274e-02, -2.4372e-02,  3.8185e-02, -3.0966e-02,
        -2.5132e-02, -2.6324e-03, -1.4011e-02, -4.4423e-02, -4.5939e-02,
        -3.3504e-02, -5.8271e-02, -5.8634e-03,  1.5890e-02, -4.8063e-02,
         7.2516e-05, -1.2736e-02,  5.6359e-03,  2.5655e-02,  3.4659e-02,
        -6.1227e-02, -1.0812e-02, -7.7591e-02, -3.7923e-02, -5.1106e-03,
        -6.1405e-02,  5.8858e-02, -6.1069e-02, -6.9694e-02, -2.4728e-03,
        -3.4584e-02, -3.1165e-02, -1.3581e-02, -6.1704e-02, -4.0551e-03,
         1.7473e-02, -1.0827e-02, -3.5280e-02, -2.1241e-02,  9.0991e-03,
        -5.1856e-02, -6.8024e-02, -8.9475e-02, -6.2368e-03, -2.1825e-02,
        -8.7671e-03,  1.5360e-02, -2.2871e-02, -1.7114e-02, -6.5442e-03,
        -7.1373e-02, -4.8614e-02, -2.0651e-02, -3.3291e-02, -5.2070e-02,
         6.9972e-03, -3.4840e-02, -3.2156e-02, -3.2105e-02, -3.5985e-02,
         6.1657e-03, -2.5129e-02, -2.5221e-02, -7.2196e-03,  1.4372e-02,
        -3.1900e-02, -2.9158e-01, -3.3827e-02, -5.3

# Processor

In [20]:
def assign_graphcast_processor_weights(graphcast_model, weights):
    """Assigns weights to the GraphCast processor layers.

    Args:
        graphcast_model: The GraphCast model.
        weights: A dictionary containing the pre-trained weights.
    """
    for i in range(0, 14):
        edge_block_index = i * 2 # Edge blocks are at even indices
        node_block_index = i*2 + 1 # Node blocks are at odd indices
        
        edge_mlp = graphcast_model.processor.processor_layers[edge_block_index].edge_mlp.model
        edge_prefix = f'params:mesh_gnn/~_networks_builder/processor_edges_{i}_mesh_mlp/~'
        edge_ln_prefix = f'params:mesh_gnn/~_networks_builder/processor_edges_{i}_mesh_layer_norm'

        edge_mlp[0].weight.data.copy_(torch.tensor(weights[edge_prefix + '/linear_0:w'].T))
        edge_mlp[0].bias.data.copy_(torch.tensor(weights[edge_prefix + '/linear_0:b'].T))
        edge_mlp[2].weight.data.copy_(torch.tensor(weights[edge_prefix + '/linear_1:w'].T))
        edge_mlp[2].bias.data.copy_(torch.tensor(weights[edge_prefix + '/linear_1:b'].T))
        edge_mlp[3].weight.data.copy_(torch.tensor(weights[edge_ln_prefix + ':scale']))
        edge_mlp[3].bias.data.copy_(torch.tensor(weights[edge_ln_prefix + ':offset']))

        node_mlp = graphcast_model.processor.processor_layers[node_block_index].node_mlp.model
        node_prefix = f'params:mesh_gnn/~_networks_builder/processor_nodes_{i}_mesh_nodes_mlp/~'
        node_ln_prefix = f'params:mesh_gnn/~_networks_builder/processor_nodes_{i}_mesh_nodes_layer_norm'

        node_mlp[0].weight.data.copy_(torch.tensor(weights[node_prefix + '/linear_0:w'].T))
        node_mlp[0].bias.data.copy_(torch.tensor(weights[node_prefix + '/linear_0:b'].T))
        node_mlp[2].weight.data.copy_(torch.tensor(weights[node_prefix + '/linear_1:w'].T))
        node_mlp[2].bias.data.copy_(torch.tensor(weights[node_prefix + '/linear_1:b'].T))
        node_mlp[3].weight.data.copy_(torch.tensor(weights[node_ln_prefix + ':scale']))
        node_mlp[3].bias.data.copy_(torch.tensor(weights[node_ln_prefix + ':offset']))
assign_graphcast_processor_weights(graphcast_model, weights)

# Processor Decoder

Mesh Edge

In [21]:
graphcast_model.processor_decoder.processor_layers[0].edge_mlp.model[0].weight.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_edges_15_mesh_mlp/~/linear_0:w'].T))
graphcast_model.processor_decoder.processor_layers[0].edge_mlp.model[0].bias.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_edges_15_mesh_mlp/~/linear_0:b'].T))
graphcast_model.processor_decoder.processor_layers[0].edge_mlp.model[2].weight.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_edges_15_mesh_mlp/~/linear_1:w'].T))
graphcast_model.processor_decoder.processor_layers[0].edge_mlp.model[2].bias.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_edges_15_mesh_mlp/~/linear_1:b'].T))
graphcast_model.processor_decoder.processor_layers[0].edge_mlp.model[3].weight.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_edges_15_mesh_layer_norm:scale']))
graphcast_model.processor_decoder.processor_layers[0].edge_mlp.model[3].bias.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_edges_15_mesh_layer_norm:offset']))

tensor([ 5.3863e-03, -2.1611e-02, -1.6126e-02,  1.5753e-02,  5.5476e-03,
        -2.5053e-02,  1.9051e-03,  6.8958e-03, -8.6520e-03, -4.2983e-04,
        -3.4626e-03,  7.0913e-04,  3.7533e-03, -4.0728e-02, -7.0790e-04,
        -4.1150e-04,  1.7308e-02,  8.2289e-03,  1.0712e-02, -9.9946e-03,
        -2.0330e-02, -7.5143e-03,  1.9537e-02,  1.0133e-02, -1.4113e-03,
        -1.9241e-02, -7.6723e-03,  1.2796e-02,  1.1445e-02, -1.4114e-02,
         3.0103e-03, -9.3144e-03,  3.8750e-03,  1.1044e-02,  4.9724e-03,
         1.2399e-02, -1.4215e-02,  5.8405e-03,  8.3429e-02,  1.7952e-02,
        -6.2748e-02,  8.5904e-03,  1.9032e-02,  1.2678e-02,  1.3581e-02,
         1.1499e-02,  3.7857e-02,  4.5333e-02,  7.4511e-03, -4.7271e-04,
         1.8327e-02,  4.2287e-03,  8.5719e-03,  3.8287e-04,  2.2866e-02,
        -3.5681e-02, -4.9485e-03, -1.5651e-02, -1.9290e-02,  5.6025e-03,
        -4.9831e-03, -6.6890e-03,  4.8013e-03, -5.4323e-03, -1.4529e-02,
         1.3867e-02, -1.6772e-02, -1.9000e-02,  4.3

Mesh Nodes

In [22]:
graphcast_model.processor_decoder.processor_layers[1].node_mlp.model[0].weight.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_nodes_15_mesh_nodes_mlp/~/linear_0:w'].T))
graphcast_model.processor_decoder.processor_layers[1].node_mlp.model[0].bias.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_nodes_15_mesh_nodes_mlp/~/linear_0:b'].T))
graphcast_model.processor_decoder.processor_layers[1].node_mlp.model[2].weight.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_nodes_15_mesh_nodes_mlp/~/linear_1:w'].T))
graphcast_model.processor_decoder.processor_layers[1].node_mlp.model[2].bias.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_nodes_15_mesh_nodes_mlp/~/linear_1:b'].T))
graphcast_model.processor_decoder.processor_layers[1].node_mlp.model[3].weight.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_nodes_15_mesh_nodes_layer_norm:scale']))
graphcast_model.processor_decoder.processor_layers[1].node_mlp.model[3].bias.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_nodes_15_mesh_nodes_layer_norm:offset']))

tensor([-1.0871e-01, -7.7316e-02, -8.7827e-02, -1.1440e-01, -5.5111e-02,
        -1.2225e-02, -1.1308e-02,  4.0928e-03,  4.4065e-02, -1.3570e-02,
        -2.0054e-02,  5.8573e-02, -2.8588e-02, -1.2197e-02, -1.4968e-02,
        -1.1173e-01, -1.6163e-02, -2.3853e-02,  9.0873e-02,  3.0761e-02,
         3.4298e-03, -1.7281e-02,  2.9680e-02, -4.4881e-02,  2.1672e-02,
         4.8560e-03, -1.2419e-02, -9.4264e-02,  2.4726e-03,  2.4020e-03,
         9.3607e-03, -2.9225e-02, -9.7995e-03, -1.4239e-01, -2.5994e-02,
        -7.3445e-02,  2.2888e-02,  1.7775e-03, -6.8428e-02,  1.1496e-02,
        -8.5512e-03,  3.3001e-02,  8.4378e-02, -4.7830e-02, -6.1255e-02,
        -9.1438e-02, -3.4952e-02, -3.8411e-02, -2.8596e-02, -3.3724e-02,
        -1.0048e-01, -2.0078e-01, -1.7071e-02,  2.4902e-02,  1.6675e-02,
        -1.0283e-01,  5.2374e-02, -6.8206e-02, -4.8982e-03, -9.6962e-02,
        -2.8706e-02,  3.5666e-02,  1.6295e-02, -5.3567e-02, -8.2386e-03,
        -1.2852e-02, -6.7512e-02, -1.0639e-01, -5.6

# MeshGraph Decoder

Nodes

In [23]:
graphcast_model.decoder.edge_mlp.model[0].weight.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/processor_edges_0_mesh2grid_mlp/~/linear_0:w'].T))
graphcast_model.decoder.edge_mlp.model[0].bias.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/processor_edges_0_mesh2grid_mlp/~/linear_0:b'].T))
graphcast_model.decoder.edge_mlp.model[2].weight.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/processor_edges_0_mesh2grid_mlp/~/linear_1:w'].T))
graphcast_model.decoder.edge_mlp.model[2].bias.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/processor_edges_0_mesh2grid_mlp/~/linear_1:b'].T))
graphcast_model.decoder.edge_mlp.model[3].weight.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/processor_edges_0_mesh2grid_layer_norm:scale']))
graphcast_model.decoder.edge_mlp.model[3].bias.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/processor_edges_0_mesh2grid_layer_norm:offset']))

tensor([-6.9499e-02, -2.1915e-01, -6.7888e-02,  6.8635e-02, -2.6929e-02,
        -1.6082e-01,  5.8076e-03, -8.8199e-05,  4.0846e-02, -1.2064e-01,
        -2.8612e-01,  6.1079e-02, -1.2635e-01,  7.4782e-02,  4.0062e-02,
         1.9727e-01, -1.4151e-01,  3.0853e-02,  1.4513e-01, -1.0133e-01,
         1.1758e-01,  1.1591e-01, -9.5094e-02,  2.7194e-01, -8.2427e-02,
         8.7095e-02,  6.5416e-02, -2.0993e-02,  2.6339e-02, -4.4607e-03,
        -9.4912e-02,  8.3093e-02,  1.7190e-01,  1.0266e-03, -9.8049e-02,
        -4.9913e-04, -3.2414e-01, -3.5092e-01,  2.3040e-02, -5.1912e-02,
         6.1927e-02,  9.3399e-02, -9.1477e-02,  1.7415e-01,  1.6721e-01,
        -1.4577e-01, -2.2744e-02, -4.7163e-02,  6.9644e-02,  1.1831e-03,
        -7.1498e-02,  8.3990e-03, -5.0811e-02,  5.5948e-02,  3.1923e-02,
         7.1211e-03, -1.1630e-01, -5.8603e-02,  1.8864e-01,  1.4933e-01,
        -1.8798e-01,  1.6670e-01, -2.4795e-01, -6.0754e-02,  4.6276e-02,
         1.5692e-01, -2.0187e-01,  1.6341e-01,  9.3

Edges

In [24]:
graphcast_model.decoder.node_mlp.model[0].weight.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/processor_nodes_0_grid_nodes_mlp/~/linear_0:w'].T))
graphcast_model.decoder.node_mlp.model[0].bias.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/processor_nodes_0_grid_nodes_mlp/~/linear_0:b'].T))
graphcast_model.decoder.node_mlp.model[2].weight.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/processor_nodes_0_grid_nodes_mlp/~/linear_1:w'].T))
graphcast_model.decoder.node_mlp.model[2].bias.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/processor_nodes_0_grid_nodes_mlp/~/linear_1:b'].T))
graphcast_model.decoder.node_mlp.model[3].weight.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/processor_nodes_0_grid_nodes_layer_norm:scale']))
graphcast_model.decoder.node_mlp.model[3].bias.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/processor_nodes_0_grid_nodes_layer_norm:offset']))

tensor([ 4.6592e-03,  9.7750e-03, -3.5077e-02,  1.2009e-01,  4.4900e-02,
        -5.5267e-02, -8.1433e-02,  1.4173e-01, -4.0498e-02,  1.1422e-01,
        -4.6109e-02, -8.5512e-02, -2.3763e-02, -2.2976e-02, -2.4683e-01,
         3.2918e-02, -3.5980e-02,  7.3165e-02, -2.3694e-02, -2.7004e-02,
        -1.2695e-02, -2.2475e-02, -6.6832e-02,  1.2240e-01,  3.7617e-02,
         1.3233e-02, -2.5558e-04,  1.1008e-02, -1.7650e-01, -7.1698e-02,
        -2.8411e-02, -7.7825e-02, -2.5930e-02,  5.3457e-02,  1.3277e-01,
        -1.9371e-01,  3.4113e-02,  1.4135e-02,  1.4655e-01, -5.4623e-02,
        -4.1015e-02, -1.1034e-01,  3.1889e-02, -4.5904e-02,  8.8593e-03,
        -1.2311e-02, -1.6510e-01, -1.8149e-02, -2.6313e-02, -1.0355e-01,
         5.4568e-03, -6.5300e-02,  4.1869e-02, -1.1741e-01, -4.6406e-02,
         1.3140e-01,  2.8854e-02,  3.6395e-02,  8.8289e-02,  1.2792e-01,
         1.4610e-01,  7.8547e-02,  2.6467e-02,  7.7910e-01,  7.0812e-02,
         3.9462e-02,  3.8485e-02,  1.9107e-01, -3.2

In [25]:
graphcast_model.finale.model[0].weight.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/decoder_nodes_grid_nodes_mlp/~/linear_0:w'].T))
graphcast_model.finale.model[0].bias.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/decoder_nodes_grid_nodes_mlp/~/linear_0:b'].T))
graphcast_model.finale.model[2].weight.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/decoder_nodes_grid_nodes_mlp/~/linear_1:w'].T))
graphcast_model.finale.model[2].bias.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/decoder_nodes_grid_nodes_mlp/~/linear_1:b'].T))

tensor([ 4.3129e-02,  9.4356e-03,  7.7088e-03, -6.3433e-01, -4.2468e-01,
        -6.0086e-01, -2.1238e-01, -1.8432e-01, -6.3913e-02,  7.1526e-02,
         1.0554e-02, -4.7010e-02, -1.1688e-02, -7.6908e-03, -2.3043e-02,
        -2.5892e-02, -2.5546e-02, -2.3025e-02, -2.1592e-02, -2.2544e-02,
        -2.7155e-02, -2.6882e-02, -2.1433e-02, -2.4508e-02, -2.5328e-02,
        -2.4285e-02, -2.6203e-02, -2.4349e-02, -2.1558e-02, -1.6963e-02,
        -1.4625e-02, -1.6505e-02, -1.3925e-02, -1.0640e-02, -1.2111e-02,
        -9.0529e-03, -8.6392e-03, -5.8807e-03, -2.8830e-03,  3.9719e-03,
         6.8568e-03, -1.3938e-01,  5.1073e-02, -2.6137e-01,  8.1823e-02,
        -5.3068e-01,  3.3440e-01, -2.2800e-01,  1.5434e-01, -2.3349e-02,
        -2.9482e-01, -2.8437e-03, -3.0998e-03,  1.1050e-02,  1.7242e-02,
         1.7588e-02,  6.0783e-03,  3.9358e-03, -6.8795e-03, -1.0334e-02,
        -1.6734e-02,  2.5392e-03, -6.7736e-03, -2.3577e-02, -2.0795e-02,
        -8.8171e-03, -2.3856e-02, -2.2121e-02, -4.3

In [26]:
for name in keys:
    if name not in used_names and 'mesh_gnn' in name:
        used_names.append(name)

In [27]:
for name in keys:
    if (name not in used_names) and ('processor_edges_0_mesh2grid' in name):
        used_names.append(name)

In [28]:
for name in keys:
    if (name not in used_names) and ('processor_nodes_0_grid_nodes' in name):
        used_names.append(name)

In [29]:
for name in keys:
    if (name not in used_names) and ('decoder_nodes_grid_nodes' in name):
        used_names.append(name)

In [30]:
for name in keys:
    if name not in used_names:
        print(name)

params:mesh2grid_gnn/~_networks_builder/decoder_nodes_mesh_nodes_mlp/~/linear_1:b
params:mesh2grid_gnn/~_networks_builder/decoder_nodes_mesh_nodes_mlp/~/linear_1:w
params:mesh2grid_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_layer_norm:offset
params:mesh2grid_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_layer_norm:scale
params:mesh2grid_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_mlp/~/linear_0:b
params:mesh2grid_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_mlp/~/linear_0:w
params:mesh2grid_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_mlp/~/linear_1:b
params:mesh2grid_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_mlp/~/linear_1:w


In [32]:
graphcast_model.save('gc_weights/graphcast_0.25_0.13.mdlus')

In [33]:
graphcast_model.load('gc_weights/graphcast_0.25_0.13.mdlus')

/home/saptarishi.dhanuka_asp25/miniconda3/envs/modulus/lib/python3.10/site-packages/modulus/models/module.py:314: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model_dict = 