In [1]:
import modulus.models.graphcast
import numpy as np
import torch

In [2]:
weights = np.load('gc_weights/graphcast_0.25_13.npz')
keys = list(weights.keys())

In [3]:
graphcast_model = modulus.models.graphcast.GraphCastNet(input_dim_grid_nodes=184, output_dim_grid_nodes=83)

In [4]:
for name in keys[:]:
    if ('task_config' in name or 'model_config' in name or 'description' in name or 'license' in name):
        keys.remove(name)
print(len(keys))

264


In [5]:
used_names = []
count = 0
for name in keys:
    if 'encoder' in name:
        count+=1
        used_names.append(name)

In [6]:
for name in keys:
    if 'grid2mesh' in name and name not in used_names:
        used_names.append(name)
        count +=1

# Feature Embedder

In [7]:
weight = weights['params:grid2mesh_gnn/~_networks_builder/encoder_nodes_mesh_nodes_mlp/~/linear_0:w']

Grid Nodes

In [8]:
graphcast_model.encoder_embedder.grid_node_mlp.model[0].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_nodes_grid_nodes_mlp/~/linear_0:w']).T)
graphcast_model.encoder_embedder.grid_node_mlp.model[0].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_nodes_grid_nodes_mlp/~/linear_0:b']).T)
graphcast_model.encoder_embedder.grid_node_mlp.model[2].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_nodes_grid_nodes_mlp/~/linear_1:w']).T)
graphcast_model.encoder_embedder.grid_node_mlp.model[2].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_nodes_grid_nodes_mlp/~/linear_1:b']).T)
graphcast_model.encoder_embedder.grid_node_mlp.model[3].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_nodes_grid_nodes_layer_norm:offset']))
graphcast_model.encoder_embedder.grid_node_mlp.model[3].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_nodes_grid_nodes_layer_norm:scale']))

/tmp/ipykernel_1485682/576067370.py:2: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3697.)
  graphcast_model.encoder_embedder.grid_node_mlp.model[0].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_nodes_grid_nodes_mlp/~/linear_0:b']).T)


tensor([0.4050, 1.0185, 0.2639, 0.6939, 0.5625, 0.2234, 1.7132, 0.7127, 1.5157,
        0.1700, 0.1548, 1.0468, 0.7618, 0.1838, 1.6965, 1.3558, 1.0468, 1.0403,
        1.2996, 0.3703, 1.0924, 1.3245, 0.7103, 0.6535, 1.6490, 0.7066, 1.2898,
        0.2483, 1.9326, 0.8979, 0.5828, 0.8203, 1.0159, 1.0317, 0.6476, 1.0840,
        1.4928, 1.1793, 1.9839, 1.0892, 0.3825, 0.2972, 0.5981, 1.0588, 0.8228,
        0.6836, 0.1623, 0.9595, 1.6398, 1.0058, 0.2923, 0.3607, 0.4788, 1.7357,
        0.2442, 1.0316, 0.3501, 0.2861, 1.0554, 0.8384, 0.1398, 0.3183, 0.8567,
        0.4830, 1.6134, 0.3951, 0.7035, 0.5681, 0.9164, 0.5190, 1.5225, 0.6749,
        1.9098, 1.5808, 2.0234, 1.6050, 0.6859, 0.4826, 1.5021, 0.6787, 0.1454,
        1.1638, 0.3258, 0.9016, 0.3317, 0.4928, 0.6485, 1.7336, 0.6308, 0.6970,
        0.5572, 0.5583, 0.8334, 0.3535, 0.7963, 1.4806, 1.1126, 0.4384, 1.2683,
        0.3239, 1.5880, 0.5855, 0.4223, 0.2100, 1.5547, 0.2907, 1.7745, 0.7039,
        0.5464, 0.9762, 1.5207, 1.1128, 

Mesh Nodes

In [9]:
# Mesh Nodes are padded by prepending on zero
graphcast_model.encoder_embedder.mesh_node_mlp.model[0].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_nodes_mesh_nodes_mlp/~/linear_0:w'][-3:]).T)
graphcast_model.encoder_embedder.mesh_node_mlp.model[0].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_nodes_mesh_nodes_mlp/~/linear_0:b']).T)
graphcast_model.encoder_embedder.mesh_node_mlp.model[2].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_nodes_mesh_nodes_mlp/~/linear_1:w']).T)
graphcast_model.encoder_embedder.mesh_node_mlp.model[2].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_nodes_mesh_nodes_mlp/~/linear_1:b']).T)
graphcast_model.encoder_embedder.mesh_node_mlp.model[3].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_nodes_mesh_nodes_layer_norm:offset']))
graphcast_model.encoder_embedder.mesh_node_mlp.model[3].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_nodes_mesh_nodes_layer_norm:scale']))

tensor([ 1.7543e-03,  2.0826e-04, -7.7871e-04, -7.4339e-04, -1.5629e-04,
         8.3030e-04,  5.8199e-04, -5.0254e-04,  2.3294e-04,  9.2824e-04,
        -9.4389e-04,  1.0631e-03,  1.5232e-03, -1.3754e-03, -1.8688e-04,
        -7.7407e-04, -1.3283e-05, -9.5145e-05,  3.2531e-04,  6.1952e-04,
         5.9037e-04,  4.3809e-04, -5.7368e-05,  9.9349e-06,  1.1038e-03,
         3.8343e-03, -2.0767e-05,  1.5993e-03,  3.8499e-04, -2.1469e-05,
         4.8750e-05, -7.7146e-05,  1.2122e-04, -4.4197e-05, -1.1396e-03,
        -5.1422e-04,  5.2787e-04,  3.7695e-04,  4.4918e-04, -3.0903e-04,
        -1.9765e-04,  9.2967e-05,  6.6420e-05, -3.6093e-04, -4.3160e-05,
         4.9526e-04, -8.2084e-04,  6.0679e-04,  4.3183e-04, -1.7047e-03,
         2.5290e-04, -2.0169e-03,  1.7409e-03,  1.6698e-04,  2.2721e-04,
         2.4654e-04,  1.7819e-04,  3.9435e-04, -4.2279e-04,  3.5508e-04,
        -1.1036e-03,  5.2707e-04, -2.4743e-03,  4.4352e-04,  1.4742e-04,
        -1.5692e-04,  3.3921e-04,  6.6972e-04,  2.8

Mesh Edges

In [10]:
graphcast_model.encoder_embedder.mesh_edge_mlp.model[0].weight.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/encoder_edges_mesh_mlp/~/linear_0:w']).T)
graphcast_model.encoder_embedder.mesh_edge_mlp.model[0].bias.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/encoder_edges_mesh_mlp/~/linear_0:b']).T)
graphcast_model.encoder_embedder.mesh_edge_mlp.model[2].weight.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/encoder_edges_mesh_mlp/~/linear_1:w']).T)
graphcast_model.encoder_embedder.mesh_edge_mlp.model[2].bias.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/encoder_edges_mesh_mlp/~/linear_1:b']).T)
graphcast_model.encoder_embedder.mesh_edge_mlp.model[3].bias.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/encoder_edges_mesh_layer_norm:offset']))
graphcast_model.encoder_embedder.mesh_edge_mlp.model[3].weight.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/encoder_edges_mesh_layer_norm:scale']))

tensor([ 3.9946e-05, -7.4284e-06,  1.8910e-04,  1.0702e+00, -7.3044e-05,
        -4.6167e-04, -4.5162e-04, -5.3307e-05,  1.0854e-04,  1.0937e-04,
         7.3736e-05, -3.5498e-04,  2.0868e-04, -3.0525e-05, -1.9290e-04,
         1.9390e-04, -1.1411e-04,  1.4197e+00, -1.4161e-04,  2.1946e-04,
        -1.6959e-04, -1.5512e-05, -1.1456e-04, -1.3905e-04,  3.7008e-04,
         6.9042e-05,  3.3890e-04,  2.2759e+00,  2.9944e-04,  6.9023e-04,
         2.1117e-04, -2.7439e-04, -2.5401e-04, -1.0898e-04, -1.2185e-04,
         1.7909e-04, -1.4407e-04, -2.2998e-05,  2.1078e-04,  1.5707e+00,
        -4.7403e-04,  1.2635e+00, -1.3912e-04, -2.7594e-05,  3.8286e-04,
         8.1087e-05,  3.2893e-04,  3.3685e-05, -1.4697e-04,  4.2408e-04,
         6.1474e-04,  1.1287e+00, -5.9633e-05, -1.1955e-05,  9.4367e-05,
         9.9936e-05, -5.4796e-05,  2.0563e-04, -1.9703e-04,  6.4643e-01,
        -8.9555e-05, -1.7744e-04, -1.7379e-04, -1.1813e-04,  1.4791e-04,
         4.3159e-04, -4.0054e-04, -3.1482e-05,  9.3

Grid2Mesh Edges

In [11]:
graphcast_model.encoder_embedder.grid2mesh_edge_mlp.model[0].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_edges_grid2mesh_mlp/~/linear_0:w']).T)
graphcast_model.encoder_embedder.grid2mesh_edge_mlp.model[0].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_edges_grid2mesh_mlp/~/linear_0:b']).T)
graphcast_model.encoder_embedder.grid2mesh_edge_mlp.model[2].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_edges_grid2mesh_mlp/~/linear_1:w']).T)
graphcast_model.encoder_embedder.grid2mesh_edge_mlp.model[2].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_edges_grid2mesh_mlp/~/linear_1:b']).T)
graphcast_model.encoder_embedder.grid2mesh_edge_mlp.model[3].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_edges_grid2mesh_layer_norm:offset']))
graphcast_model.encoder_embedder.grid2mesh_edge_mlp.model[3].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/encoder_edges_grid2mesh_layer_norm:scale']))

tensor([ 6.6846e-03,  2.3784e-01, -5.2061e-04, -6.7779e-03,  3.0251e-01,
         2.2138e-01,  6.0163e-01, -4.3630e-04,  4.7775e-01,  2.6735e-01,
         4.3648e-04,  3.1039e-01,  3.6225e-01,  3.5927e-01,  2.6680e-01,
         3.7667e-01,  1.8137e-01,  1.1849e+00,  3.1827e-01,  3.1943e-01,
        -4.8167e-03,  3.7563e-03,  2.9872e-01,  2.4437e-01,  2.1486e-01,
         5.6140e-03,  4.7951e-01,  3.4629e-01,  2.7443e-01,  3.7567e-01,
         1.5694e-01, -1.5395e-04,  2.6350e-03,  3.0030e-01,  3.3854e-01,
         2.2831e-01,  2.2141e-01,  2.6242e-01,  3.1277e-01,  4.0536e-01,
         5.0121e-03,  4.8265e-03,  2.6939e-01,  3.8025e-01,  3.1934e-01,
         4.0520e-03,  7.0748e-01,  2.3783e-03,  3.0164e-01,  2.8341e-01,
         3.1002e-01,  2.8115e-01,  1.4916e-03,  6.6504e-01,  2.5919e-01,
         2.0429e-01,  3.3562e-01,  4.3253e-01,  3.7142e-01,  4.1134e-01,
         3.2757e-01,  2.0753e-01,  3.5034e-01,  2.3298e-01,  1.2055e+00,
         3.5606e-01,  2.9207e-01,  6.2183e-04, -4.6

Mesh2Grid Edges

In [12]:
graphcast_model.decoder_embedder.mesh2grid_edge_mlp.model[0].weight.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/encoder_edges_mesh2grid_mlp/~/linear_0:w']).T)
graphcast_model.decoder_embedder.mesh2grid_edge_mlp.model[0].bias.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/encoder_edges_mesh2grid_mlp/~/linear_0:b']).T)
graphcast_model.decoder_embedder.mesh2grid_edge_mlp.model[2].weight.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/encoder_edges_mesh2grid_mlp/~/linear_1:w']).T)
graphcast_model.decoder_embedder.mesh2grid_edge_mlp.model[2].bias.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/encoder_edges_mesh2grid_mlp/~/linear_1:b']).T)
graphcast_model.decoder_embedder.mesh2grid_edge_mlp.model[3].bias.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/encoder_edges_mesh2grid_layer_norm:offset']))
graphcast_model.decoder_embedder.mesh2grid_edge_mlp.model[3].weight.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/encoder_edges_mesh2grid_layer_norm:scale']))

tensor([3.8250e-01, 4.2827e-01, 5.4011e-01, 4.4798e-01, 6.7625e-01, 3.5306e-01,
        5.2360e-01, 5.1354e-01, 3.2725e-01, 2.6268e-01, 5.2570e-01, 3.7999e-01,
        5.1877e-01, 4.8654e-01, 1.8171e+00, 5.1699e-01, 3.9459e-01, 1.9952e-01,
        1.9900e-01, 5.3233e-01, 3.6699e-01, 2.4138e-01, 2.1419e+00, 5.7789e-01,
        1.6988e+00, 5.9899e-01, 5.2869e-01, 2.4644e-01, 2.0344e+00, 3.7989e-01,
        3.8188e-01, 1.5437e-01, 3.9001e-01, 4.9472e-01, 1.9739e-01, 1.3656e-01,
        4.4628e-01, 3.9525e-01, 4.0429e-01, 5.1255e-01, 4.3094e-01, 2.8334e-01,
        3.2198e-01, 4.4652e-01, 5.1268e-01, 1.8864e-01, 1.9427e+00, 5.6462e-01,
        3.1230e-01, 2.2516e-01, 5.3027e-01, 4.2316e-01, 1.2750e+00, 4.4890e-01,
        4.5486e-01, 3.8185e-01, 2.8202e-01, 4.9027e-01, 2.0516e-01, 2.9454e-01,
        3.6546e-01, 3.0864e-01, 5.1093e-01, 5.2660e-01, 3.3370e-01, 6.1378e-01,
        2.8177e-01, 4.8195e-01, 1.5514e-01, 2.1651e-01, 4.1756e-01, 4.6343e-01,
        2.1512e-01, 1.7555e-01, 1.4293e-

# Mesh Graph Encoder

Processor Edge MLP

In [13]:
graphcast_model.encoder.edge_mlp.model[0].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_edges_0_grid2mesh_mlp/~/linear_0:w']).T)
graphcast_model.encoder.edge_mlp.model[0].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_edges_0_grid2mesh_mlp/~/linear_0:b']).T)
graphcast_model.encoder.edge_mlp.model[2].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_edges_0_grid2mesh_mlp/~/linear_1:w']).T)
graphcast_model.encoder.edge_mlp.model[2].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_edges_0_grid2mesh_mlp/~/linear_1:b']).T)
graphcast_model.encoder.edge_mlp.model[3].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_edges_0_grid2mesh_layer_norm:offset']))
graphcast_model.encoder.edge_mlp.model[3].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_edges_0_grid2mesh_layer_norm:scale']))

tensor([ 7.2060e-01,  4.6485e-01,  9.4693e-01,  2.8084e-04,  4.0726e-01,
         7.5154e-01,  2.6604e-01,  2.3712e-01, -2.6312e-04,  1.1919e+00,
         4.6429e-01,  4.0736e-01,  2.8496e-01, -3.1471e-04,  2.1489e-01,
         1.2944e-02,  7.2820e-01,  1.5969e-04,  3.0906e-01,  6.0252e-01,
         8.3557e-01,  4.8880e-01, -1.1939e-04,  3.5873e-04,  3.8189e-01,
         2.1515e-01,  5.3935e-01,  4.1415e-01,  4.9125e-01,  3.7754e-04,
         5.7011e-01,  3.8488e-01,  8.6551e-01,  2.4075e-01,  1.5371e-04,
         2.7532e-01,  3.0267e-01,  3.6288e-01,  4.4430e-05,  7.8818e-01,
         3.1672e-01,  2.5540e-01,  3.0457e-01,  8.1840e-02, -1.1657e-03,
         1.0588e+00,  4.9670e-03,  4.9558e-05, -2.3263e-04,  1.3286e-04,
         2.8250e-01,  8.8483e-01,  4.9682e-01,  9.4472e-01, -1.1270e-04,
         4.8534e-01,  3.9771e-01,  1.2724e+00,  4.6699e-01,  2.8291e-01,
         5.9381e-03,  2.6191e-01,  2.2971e-01,  3.2834e-04,  4.2675e-01,
         2.4637e-01,  2.3964e-01,  1.4094e-01,  7.9

Processor Grid Node MLP

In [14]:
graphcast_model.encoder.src_node_mlp.model[0].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_nodes_0_grid_nodes_mlp/~/linear_0:w']).T)
graphcast_model.encoder.src_node_mlp.model[0].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_nodes_0_grid_nodes_mlp/~/linear_0:b']).T)
graphcast_model.encoder.src_node_mlp.model[2].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_nodes_0_grid_nodes_mlp/~/linear_1:w']).T)
graphcast_model.encoder.src_node_mlp.model[2].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_nodes_0_grid_nodes_mlp/~/linear_1:b']).T)
graphcast_model.encoder.src_node_mlp.model[3].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_nodes_0_grid_nodes_layer_norm:offset']))
graphcast_model.encoder.src_node_mlp.model[3].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_nodes_0_grid_nodes_layer_norm:scale']))

tensor([6.3328e-01, 6.2947e-01, 7.7504e-01, 1.8884e+00, 9.3284e-01, 5.5369e-01,
        1.1557e-01, 4.6113e-01, 8.2912e-01, 1.4983e+00, 5.9834e-01, 8.4780e-01,
        7.1792e-01, 5.8790e-01, 1.3884e-01, 1.0017e+00, 6.3709e-01, 7.7234e-02,
        1.8231e-01, 7.9513e-01, 8.3382e-01, 1.0897e-01, 5.0586e-01, 1.4418e+00,
        6.9419e-03, 5.8814e-01, 8.8651e-02, 7.5231e-01, 2.0759e-02, 5.6455e-01,
        1.0117e+00, 7.7746e-01, 4.9563e-01, 1.2257e+00, 7.2808e-01, 6.2142e-03,
        4.8407e-02, 9.3853e-02, 1.5788e-02, 9.1533e-01, 7.8426e-01, 7.6443e-01,
        8.3052e-01, 1.3022e-01, 7.5035e-01, 1.0075e+00, 5.4409e-01, 1.1250e+00,
        7.2047e-02, 7.4743e-02, 7.9383e-01, 5.6485e-01, 7.4957e-01, 3.4733e-04,
        5.3982e-01, 6.9649e-01, 1.6934e+00, 6.5175e-01, 7.1608e-01, 8.4761e-01,
        1.6748e+00, 6.7111e-01, 2.7395e-01, 6.0631e-01, 3.8332e-02, 4.4677e+00,
        7.2817e-01, 4.9447e-01, 7.1227e-01, 6.9902e-01, 1.0546e-01, 6.5565e-01,
        8.4265e-02, 9.6755e-02, 1.4195e-

Processor Mesh Node MLP

In [15]:
graphcast_model.encoder.dst_node_mlp.model[0].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_mlp/~/linear_0:w']).T)
graphcast_model.encoder.dst_node_mlp.model[0].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_mlp/~/linear_0:b']).T)
graphcast_model.encoder.dst_node_mlp.model[2].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_mlp/~/linear_1:w']).T)
graphcast_model.encoder.dst_node_mlp.model[2].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_mlp/~/linear_1:b']).T)
graphcast_model.encoder.dst_node_mlp.model[3].bias.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_layer_norm:offset']))
graphcast_model.encoder.dst_node_mlp.model[3].weight.data.copy_(torch.tensor(weights['params:grid2mesh_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_layer_norm:scale']))

tensor([0.7760, 0.6515, 0.4104, 0.7361, 0.6992, 0.7176, 0.8034, 0.5252, 0.9703,
        0.7250, 2.2366, 0.8861, 1.4454, 0.5661, 1.1929, 0.6284, 0.6218, 0.4023,
        0.7869, 0.7144, 0.9038, 1.2207, 0.7129, 0.7332, 1.3946, 1.3870, 1.6135,
        0.8459, 0.8517, 0.6194, 1.4647, 0.5474, 0.9288, 0.7481, 1.8255, 0.4935,
        1.0317, 0.6897, 0.8601, 0.8372, 0.2391, 0.8895, 0.6914, 0.8815, 0.3916,
        0.8259, 1.8272, 0.5060, 0.6447, 1.2742, 0.3959, 0.7392, 0.6700, 0.9422,
        0.7711, 0.8410, 0.7808, 0.7092, 0.6359, 0.7798, 1.0248, 0.5888, 0.7951,
        0.5021, 0.8312, 0.7729, 0.4206, 0.7257, 1.7272, 0.9397, 0.6893, 1.0921,
        0.5177, 1.1924, 0.3872, 2.1139, 0.5528, 1.2011, 0.9027, 0.7456, 0.9115,
        0.9323, 1.2127, 0.9975, 1.0284, 0.7246, 2.0671, 1.0163, 0.5447, 1.0941,
        0.7329, 1.2480, 0.6282, 0.9547, 0.8665, 1.8723, 0.7275, 0.4164, 0.3548,
        0.4709, 0.9945, 0.7193, 0.7768, 0.1336, 1.1975, 0.5439, 0.9287, 0.6600,
        0.5841, 0.7230, 0.2379, 0.7415, 

# Processor Encoder

Mesh Edge

In [16]:
graphcast_model.processor_encoder.processor_layers[0].edge_mlp.model[0].weight.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_edges_0_mesh_mlp/~/linear_0:w'].T))
graphcast_model.processor_encoder.processor_layers[0].edge_mlp.model[0].bias.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_edges_0_mesh_mlp/~/linear_0:b'].T))
graphcast_model.processor_encoder.processor_layers[0].edge_mlp.model[2].weight.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_edges_0_mesh_mlp/~/linear_1:w'].T))
graphcast_model.processor_encoder.processor_layers[0].edge_mlp.model[2].bias.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_edges_0_mesh_mlp/~/linear_1:b'].T))
graphcast_model.processor_encoder.processor_layers[0].edge_mlp.model[3].weight.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_edges_0_mesh_layer_norm:scale']))
graphcast_model.processor_encoder.processor_layers[0].edge_mlp.model[3].bias.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_edges_0_mesh_layer_norm:offset']))

tensor([ 1.5651e-01,  2.3367e-01, -1.7116e-01,  1.1125e-01, -2.8221e-02,
        -8.0744e-02,  1.3076e-01,  1.7745e-02,  3.7753e-02,  8.3231e-03,
         1.4067e-01, -6.0106e-02, -2.9804e-02,  4.1252e-02,  4.9207e-02,
        -2.2544e-01, -2.2601e-02, -1.5458e-01,  1.0419e-01, -6.8222e-02,
         3.8364e-02,  3.1840e-03,  7.0409e-02,  3.1495e-02, -1.0586e-01,
        -2.6741e-02,  2.8579e-02,  7.2805e-02,  3.6333e-02, -2.1698e-01,
         6.0493e-02, -3.8980e-01, -7.8300e-02,  3.0838e-02, -1.0776e-01,
        -1.4268e-01,  1.6990e-02,  2.2694e-03, -9.1872e-02, -6.0321e-02,
        -1.7125e-01, -4.0726e-02,  3.4208e-03,  1.6961e-02,  1.1695e-01,
         2.2881e-02, -1.6509e-01, -8.1747e-03,  3.4185e-02, -1.1521e-01,
        -4.5044e-03, -1.4953e-01,  8.2117e-02,  2.6055e-01, -4.9732e-02,
         1.5984e-01,  1.1430e-01,  2.6558e-01,  4.9254e-02, -2.9234e-02,
        -7.7360e-02, -1.2124e-01,  2.4221e-01,  1.9404e-01, -1.1672e-01,
         3.5667e-02,  1.7707e-01,  2.5028e-01, -6.5

Mesh Node

In [17]:
graphcast_model.processor_encoder.processor_layers[1].node_mlp.model[0].weight.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_mlp/~/linear_0:w'].T))
graphcast_model.processor_encoder.processor_layers[1].node_mlp.model[0].bias.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_mlp/~/linear_0:b'].T))
graphcast_model.processor_encoder.processor_layers[1].node_mlp.model[2].weight.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_mlp/~/linear_1:w'].T))
graphcast_model.processor_encoder.processor_layers[1].node_mlp.model[2].bias.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_mlp/~/linear_1:b'].T))
graphcast_model.processor_encoder.processor_layers[1].node_mlp.model[3].weight.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_layer_norm:scale']))
graphcast_model.processor_encoder.processor_layers[1].node_mlp.model[3].bias.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_layer_norm:offset']))

tensor([-2.3794e-02, -2.2729e-02, -3.1346e-02, -8.8025e-02, -2.0657e-02,
        -6.2858e-02, -2.7796e-03, -9.8561e-03, -5.3672e-02, -4.0495e-02,
        -7.3615e-02,  1.6900e-02,  1.0971e-02, -1.0074e-01,  3.3907e-02,
         9.0483e-03,  1.2699e-02, -2.4321e-01, -3.0153e-02, -4.1469e-02,
        -1.4398e-02, -3.3263e-02,  3.1483e-02, -5.7304e-02, -1.4717e-02,
        -4.3876e-02,  2.7807e-02, -7.1675e-02, -2.2101e-02, -1.3558e-02,
        -8.8794e-03, -5.7043e-02, -4.5784e-02, -1.8754e-02, -1.9720e-01,
         1.2206e-02, -7.8046e-03,  1.1360e-03, -4.3066e-02, -8.3378e-03,
        -1.7373e-02,  1.4002e-02, -1.8122e-02, -2.0473e-02, -3.7536e-02,
        -5.3087e-02,  3.8419e-03, -2.6904e-02, -8.3033e-02,  4.6591e-03,
        -5.5319e-04,  1.4095e-02, -1.3644e-02, -1.5282e-02, -3.3389e-02,
        -1.0719e-01, -2.2429e-02, -1.7348e-03, -1.1726e-02,  6.6532e-02,
        -1.5624e-02,  3.5724e-03,  1.8402e-02, -5.4250e-02, -5.6215e-02,
         4.5442e-02,  5.0305e-02, -2.4700e-02, -1.1

# Processor

In [18]:
def assign_graphcast_processor_weights(graphcast_model, weights):
    """Assigns weights to the GraphCast processor layers.

    Args:
        graphcast_model: The GraphCast model.
        weights: A dictionary containing the pre-trained weights.
    """
    for i in range(0, 14):
        edge_block_index = i * 2 # Edge blocks are at even indices
        node_block_index = i*2 + 1 # Node blocks are at odd indices
        
        edge_mlp = graphcast_model.processor.processor_layers[edge_block_index].edge_mlp.model
        edge_prefix = f'params:mesh_gnn/~_networks_builder/processor_edges_{i}_mesh_mlp/~'
        edge_ln_prefix = f'params:mesh_gnn/~_networks_builder/processor_edges_{i}_mesh_layer_norm'

        edge_mlp[0].weight.data.copy_(torch.tensor(weights[edge_prefix + '/linear_0:w'].T))
        edge_mlp[0].bias.data.copy_(torch.tensor(weights[edge_prefix + '/linear_0:b'].T))
        edge_mlp[2].weight.data.copy_(torch.tensor(weights[edge_prefix + '/linear_1:w'].T))
        edge_mlp[2].bias.data.copy_(torch.tensor(weights[edge_prefix + '/linear_1:b'].T))
        edge_mlp[3].weight.data.copy_(torch.tensor(weights[edge_ln_prefix + ':scale']))
        edge_mlp[3].bias.data.copy_(torch.tensor(weights[edge_ln_prefix + ':offset']))

        node_mlp = graphcast_model.processor.processor_layers[node_block_index].node_mlp.model
        node_prefix = f'params:mesh_gnn/~_networks_builder/processor_nodes_{i}_mesh_nodes_mlp/~'
        node_ln_prefix = f'params:mesh_gnn/~_networks_builder/processor_nodes_{i}_mesh_nodes_layer_norm'

        node_mlp[0].weight.data.copy_(torch.tensor(weights[node_prefix + '/linear_0:w'].T))
        node_mlp[0].bias.data.copy_(torch.tensor(weights[node_prefix + '/linear_0:b'].T))
        node_mlp[2].weight.data.copy_(torch.tensor(weights[node_prefix + '/linear_1:w'].T))
        node_mlp[2].bias.data.copy_(torch.tensor(weights[node_prefix + '/linear_1:b'].T))
        node_mlp[3].weight.data.copy_(torch.tensor(weights[node_ln_prefix + ':scale']))
        node_mlp[3].bias.data.copy_(torch.tensor(weights[node_ln_prefix + ':offset']))
assign_graphcast_processor_weights(graphcast_model, weights)

# Processor Decoder

Mesh Edge

In [19]:
graphcast_model.processor_decoder.processor_layers[0].edge_mlp.model[0].weight.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_edges_15_mesh_mlp/~/linear_0:w'].T))
graphcast_model.processor_decoder.processor_layers[0].edge_mlp.model[0].bias.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_edges_15_mesh_mlp/~/linear_0:b'].T))
graphcast_model.processor_decoder.processor_layers[0].edge_mlp.model[2].weight.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_edges_15_mesh_mlp/~/linear_1:w'].T))
graphcast_model.processor_decoder.processor_layers[0].edge_mlp.model[2].bias.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_edges_15_mesh_mlp/~/linear_1:b'].T))
graphcast_model.processor_decoder.processor_layers[0].edge_mlp.model[3].weight.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_edges_15_mesh_layer_norm:scale']))
graphcast_model.processor_decoder.processor_layers[0].edge_mlp.model[3].bias.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_edges_15_mesh_layer_norm:offset']))

tensor([ 1.1119e-03,  5.5293e-03,  2.9632e-03,  1.7253e-02,  1.6083e-02,
         9.4835e-03, -6.8902e-03, -6.7959e-04,  1.6535e-03, -1.2014e-03,
        -1.1061e-03, -1.5622e-04,  3.7842e-03, -4.1280e-02,  9.0461e-03,
        -1.5723e-02,  2.2245e-02,  2.4791e-02, -5.0610e-02,  9.7441e-03,
         9.8550e-03, -3.0865e-03, -6.3663e-03, -2.1433e-02,  1.5631e-02,
        -3.2685e-04,  2.7140e-02, -3.4331e-02,  1.3981e-02, -6.5720e-02,
         1.3699e-03, -2.3021e-02, -1.9229e-02,  1.3445e-02,  7.9331e-03,
        -3.1348e-02,  1.3997e-02,  5.5892e-02,  1.0199e-02, -5.1412e-03,
        -1.5821e-02, -9.0818e-02, -4.3976e-02,  2.9673e-02,  1.3594e-02,
        -4.0782e-04,  1.3123e-02, -4.7513e-03, -2.7941e-02, -3.9856e-02,
         2.5195e-02, -4.1551e-02, -2.6561e-02,  2.3535e-02,  4.1136e-02,
         2.8844e-02,  2.1937e-02,  1.0365e-03,  4.8798e-02,  1.3438e-02,
        -1.6228e-02, -8.9618e-04, -2.7241e-02,  5.6858e-03,  1.0337e-03,
        -2.7523e-02,  2.0401e-02,  2.3541e-02,  2.8

Mesh Nodes

In [20]:
graphcast_model.processor_decoder.processor_layers[1].node_mlp.model[0].weight.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_nodes_15_mesh_nodes_mlp/~/linear_0:w'].T))
graphcast_model.processor_decoder.processor_layers[1].node_mlp.model[0].bias.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_nodes_15_mesh_nodes_mlp/~/linear_0:b'].T))
graphcast_model.processor_decoder.processor_layers[1].node_mlp.model[2].weight.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_nodes_15_mesh_nodes_mlp/~/linear_1:w'].T))
graphcast_model.processor_decoder.processor_layers[1].node_mlp.model[2].bias.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_nodes_15_mesh_nodes_mlp/~/linear_1:b'].T))
graphcast_model.processor_decoder.processor_layers[1].node_mlp.model[3].weight.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_nodes_15_mesh_nodes_layer_norm:scale']))
graphcast_model.processor_decoder.processor_layers[1].node_mlp.model[3].bias.data.copy_(torch.tensor(weights['params:mesh_gnn/~_networks_builder/processor_nodes_15_mesh_nodes_layer_norm:offset']))

tensor([ 2.2216e-02,  1.4907e-02, -4.5943e-02,  4.9278e-02, -3.7035e-02,
        -4.6914e-02,  3.9210e-02,  2.4675e-02,  7.4058e-03, -4.7268e-03,
        -4.7701e-03,  5.2463e-02,  3.5688e-02, -7.5529e-03,  9.9949e-02,
         6.6105e-03, -4.1712e-02,  2.9334e-02,  5.8685e-02,  4.5143e-02,
         1.3228e-02,  3.8383e-02, -1.8875e-03,  5.2891e-02, -3.8394e-02,
         1.4207e-02,  2.1851e-02, -5.1195e-02,  2.4354e-02,  4.6502e-02,
        -4.2015e-02,  1.5560e-01,  3.3387e-02,  4.1091e-02,  3.8577e-02,
         4.8384e-02,  1.0217e-01, -5.6431e-02, -1.9102e-03,  4.8075e-02,
        -4.1696e-02,  1.5076e-02,  6.7468e-02,  3.7748e-02,  3.9320e-02,
         1.1766e-02,  3.2382e-02,  1.9739e-02,  2.7563e-01, -3.5468e-02,
         1.9313e-04, -5.1358e-02,  6.0206e-02,  9.3492e-03, -5.6243e-02,
        -2.4342e-01, -4.7182e-02,  6.8156e-03,  6.5383e-03,  9.6098e-02,
         1.7253e-03, -9.8926e-03, -4.5454e-02,  3.5284e-02,  1.8108e-02,
        -9.5524e-03, -6.9311e-02,  1.0190e-01,  7.3

# MeshGraph Decoder

Nodes

In [21]:
graphcast_model.decoder.edge_mlp.model[0].weight.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/processor_edges_0_mesh2grid_mlp/~/linear_0:w'].T))
graphcast_model.decoder.edge_mlp.model[0].bias.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/processor_edges_0_mesh2grid_mlp/~/linear_0:b'].T))
graphcast_model.decoder.edge_mlp.model[2].weight.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/processor_edges_0_mesh2grid_mlp/~/linear_1:w'].T))
graphcast_model.decoder.edge_mlp.model[2].bias.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/processor_edges_0_mesh2grid_mlp/~/linear_1:b'].T))
graphcast_model.decoder.edge_mlp.model[3].weight.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/processor_edges_0_mesh2grid_layer_norm:scale']))
graphcast_model.decoder.edge_mlp.model[3].bias.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/processor_edges_0_mesh2grid_layer_norm:offset']))

tensor([-5.3730e-02, -1.2343e-01, -1.0227e-01, -8.2819e-02, -4.3880e-05,
        -1.3568e-01, -1.6421e-03, -2.1382e-03, -1.0104e-02,  1.2508e-01,
         5.7600e-02, -1.8870e-01,  2.8485e-02,  2.6547e-01, -4.2161e-03,
        -1.5702e-01,  2.0050e-02,  2.0102e-01,  6.9582e-02, -2.6432e-03,
         1.3103e-01,  1.9583e-01, -1.6002e-03, -4.8351e-03,  9.1610e-02,
         3.6242e-01,  1.3048e-01,  1.3624e-01, -5.0982e-02,  8.9564e-02,
        -8.5889e-02, -7.8842e-02,  5.2565e-03,  1.3031e-01, -3.0208e-02,
        -6.0121e-02, -8.8722e-04, -1.7213e-02, -1.4135e-01,  3.4536e-02,
         4.8166e-03,  2.2517e-02,  1.1067e-01,  3.1720e-02, -4.3492e-02,
         4.6021e-02,  6.4014e-02,  5.2024e-02,  1.2149e-01,  3.2988e-03,
        -1.3018e-01,  1.8195e-01,  7.1119e-03,  1.4225e-01, -6.1227e-03,
         1.7856e-03,  7.2185e-02,  3.0201e-02,  1.8654e-01,  3.7464e-01,
         3.2198e-03,  4.0905e-01, -7.4670e-02,  4.0734e-01,  1.9014e-01,
         2.2911e-02, -7.4881e-02,  2.4867e-02,  1.3

Edges

In [22]:
graphcast_model.decoder.node_mlp.model[0].weight.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/processor_nodes_0_grid_nodes_mlp/~/linear_0:w'].T))
graphcast_model.decoder.node_mlp.model[0].bias.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/processor_nodes_0_grid_nodes_mlp/~/linear_0:b'].T))
graphcast_model.decoder.node_mlp.model[2].weight.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/processor_nodes_0_grid_nodes_mlp/~/linear_1:w'].T))
graphcast_model.decoder.node_mlp.model[2].bias.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/processor_nodes_0_grid_nodes_mlp/~/linear_1:b'].T))
graphcast_model.decoder.node_mlp.model[3].weight.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/processor_nodes_0_grid_nodes_layer_norm:scale']))
graphcast_model.decoder.node_mlp.model[3].bias.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/processor_nodes_0_grid_nodes_layer_norm:offset']))

tensor([ 1.0167e-01,  4.4624e-03,  3.4990e-04, -7.2892e-02, -1.7305e-01,
        -3.7188e-01,  6.1254e-02, -1.5029e-01,  2.4136e-02,  7.4597e-01,
        -3.1988e-02, -2.1157e-01,  1.4148e-01,  1.4189e-01,  6.6317e-02,
        -2.6960e-01, -1.3431e-02,  6.5536e-02,  3.2157e-02, -1.3877e-01,
        -1.7989e-02, -1.0163e-02,  2.0234e-02,  3.3089e-01,  1.5008e-02,
        -1.9175e-01,  2.1921e-03, -2.0368e-01,  3.1463e-02,  4.0131e-02,
         5.8887e-02,  9.4924e-02, -4.1229e-03,  3.9346e-01, -1.6909e-01,
         1.6318e-02, -6.4622e-02, -2.3506e-02, -2.0608e-02,  2.5356e-01,
        -8.4282e-02,  5.5150e-02,  1.9898e-02,  8.7703e-02, -1.2759e-01,
        -6.8173e-02,  1.5303e-01,  1.6498e-01, -1.2584e-01,  3.8330e-02,
        -4.0720e-01, -9.2091e-02, -3.6555e-02, -3.7479e-02,  3.8063e-02,
        -1.6035e-02,  1.6041e-02, -1.6069e-02, -1.9799e-01,  1.2325e-01,
        -3.6043e-01, -3.0701e-03,  9.5467e-02,  2.4328e-01, -1.9781e-02,
        -2.3694e-01,  8.7785e-02, -3.0454e-02,  9.3

In [23]:
graphcast_model.finale.model[0].weight.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/decoder_nodes_grid_nodes_mlp/~/linear_0:w'].T))
graphcast_model.finale.model[0].bias.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/decoder_nodes_grid_nodes_mlp/~/linear_0:b'].T))
graphcast_model.finale.model[2].weight.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/decoder_nodes_grid_nodes_mlp/~/linear_1:w'].T))
graphcast_model.finale.model[2].bias.data.copy_(torch.tensor(weights['params:mesh2grid_gnn/~_networks_builder/decoder_nodes_grid_nodes_mlp/~/linear_1:b'].T))

tensor([ 2.3675e-02,  6.7216e-04,  3.8251e-02,  2.5196e-03,  3.8605e-02,
         1.7370e-02,  8.7386e-03, -7.3798e-03, -1.0405e-02,  2.9624e-02,
         1.5267e-02,  4.2942e-03,  6.3257e-03,  8.3095e-03, -3.6317e-03,
         1.0970e-02,  6.6862e-03,  8.6040e-03,  1.9149e-02,  1.3613e-02,
         4.6385e-02,  1.0254e-02,  2.7846e-02,  9.3289e-04, -2.1244e-02,
        -1.4599e-02, -1.2967e-05, -3.0962e-02, -9.2258e-03, -2.7731e-02,
         1.1050e-02, -2.2682e-03,  2.1647e-02,  2.4289e-02,  8.4788e-03,
        -1.4257e-02, -1.4393e-02, -2.2269e-02, -7.4360e-03, -1.4974e-02,
        -3.0536e-02, -4.9290e-02, -4.6156e-02,  6.9818e-02, -5.7973e-03,
        -3.8701e-03, -1.1669e-02, -1.3904e-02, -7.7363e-03, -6.5199e-03,
         3.2392e-04, -8.3093e-03,  1.0474e-02,  8.4660e-03,  9.0588e-03,
         2.0806e-03,  1.7695e-02,  6.2543e-03,  2.5617e-03, -5.4022e-03,
        -5.7519e-03, -9.5471e-03, -1.2778e-02, -1.9108e-02, -8.8881e-03,
        -1.0457e-03,  7.7822e-04, -6.2466e-03,  9.2

In [24]:
for name in keys:
    if name not in used_names and 'mesh_gnn' in name:
        used_names.append(name)

In [25]:
for name in keys:
    if (name not in used_names) and ('processor_edges_0_mesh2grid' in name):
        used_names.append(name)

In [26]:
for name in keys:
    if (name not in used_names) and ('processor_nodes_0_grid_nodes' in name):
        used_names.append(name)

In [27]:
for name in keys:
    if (name not in used_names) and ('decoder_nodes_grid_nodes' in name):
        used_names.append(name)

In [28]:
for name in keys:
    if name not in used_names:
        print(name)

params:mesh2grid_gnn/~_networks_builder/decoder_nodes_mesh_nodes_mlp/~/linear_1:b
params:mesh2grid_gnn/~_networks_builder/decoder_nodes_mesh_nodes_mlp/~/linear_1:w
params:mesh2grid_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_layer_norm:offset
params:mesh2grid_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_layer_norm:scale
params:mesh2grid_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_mlp/~/linear_0:b
params:mesh2grid_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_mlp/~/linear_0:w
params:mesh2grid_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_mlp/~/linear_1:b
params:mesh2grid_gnn/~_networks_builder/processor_nodes_0_mesh_nodes_mlp/~/linear_1:w


In [29]:
graphcast_model.save('gc_weights/graphcast_0.25_13.mdlus')